### ISSUE TITLE
'UMAP' object has no attribute '_knn_search_index'. Did you mean: 'knn_search_index'?

### ISSUE THREAD

**Issue by pakiessling** [HiDiHlabs/ovrl.py#37]
```
visualizer.save("Xenium-text-visualizer.vis")

/hpcwork/p0020567/enviroments/overlpy2/lib/python3.12/site-packages/anndata/_core/aligned_df.py:68: ImplicitModificationWarning: Transforming to str index.
  warnings.warn("Transforming to str index.", ImplicitModificationWarning)
Traceback (most recent call last):
  File "/rwthfs/rz/cluster/work/rwth1209/projects/Overlpy_Manuscript/test.py", line 26, in <module>
    visualizer.save("Xenium-text-visualizer.vis")
  File "/hpcwork/p0020567/enviroments/overlpy2/lib/python3.12/site-packages/ovrlpy/_ovrlp.py", line 1206, in save
    pickle.dumps(self.embedder_2d._knn_search_index)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'UMAP' object has no attribute '_knn_search_index'. Did you mean: 'knn_search_index'?

```

Hi, bekomme den Fehler für umap-learn 0.5.7

Ist das viellecht die falsche Version?

**Comment by niklasmueboe** [comment]
Maybe it is better to pickle the whole UMAP (and also PCA) object? That way we are not dependent on future API changes in other packages.

**Comment by niklasmueboe** [comment]
The load and save functionality has been remoed with the newest release. To save/load your object you can still use the pickle module of the standard library.
